on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:

name: r-x86-exitcode

permissions: write-all

jobs:
  R-CMD-check:
    runs-on: windows-11-arm

    name: windows-11-arm

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5
      
      - name: Render Quarto doc using pre-installed x86_64 R 4.4.2
        run: |
          # $Env:Path -split ";"
          # Get-ChildItem -Path "C:\" -Name
          # Get-ChildItem -Path "C:\Program Files (x86)\" -Name
          # Get-ChildItem -Path "C:\Program Files (x86)\R\" -Name
          # Get-ChildItem -Path "C:\rtools45\" -Name
          # Remove-Item -Path "C:\rtools45\" -Recurse -Force
          # Install x86_64 RTools44
          # "Start rtools44"
          # $url = "https://cran.r-project.org/bin/windows/Rtools/rtools44/files/rtools44-6459-6401.exe"
          # Invoke-WebRequest -Uri "$url" -OutFile rtools44.exe -UseBasicParsing -UserAgent "NativeHost"
          # Start-Process -FilePath rtools44.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait
          # "Finish rtools44"
          
          # Add Rtool44 binaries to PATH
          # $ENV:PATH = "C:\rtools44\usr\bin;$ENV:PATH"
          # $Env:Path -split ";"
          
          # Install pandoc
          # choco install pandoc --no-progress
          # refreshenv

          # Install Quarto
          # choco install quarto --no-progress
          # refreshenv

          # Install TinyTeX
          $rscript = "Rscript"          
          # $args = "-e", "install.packages(c('tinytex'), repos = 'https://cloud.r-project.org/'); tinytex::install_tinytex(); tinytex::tlmgr_install(c('makeindex', 'upquote', 'inconsolata'))"
          # & $rscript $args

          # Add TinyTeX binaries to PATH
          # $ENV:PATH = "C:\Users\runneradmin\AppData\Roaming\TinyTeX\bin\windows;$ENV:PATH"
          
          # Install htmltools from source
          # $args = "-e", "install.packages(c('htmltools'), repos = 'https://cloud.r-project.org/', type = 'source');"
          # & $rscript $args
          # echo $?
          
          # Install knitr and rmarkdown
          $args = "-e", "install.packages(c('knitr', 'rmarkdown', 'rstudioapi'), repos = 'https://cloud.r-project.org/', type = 'binary');"
          & $rscript $args
          echo $?
          
          # $args = "C:\ProgramData\Chocolatey\lib\quarto\tools\share\capabilities\knitr.R"
          # & $rscript $args
          # echo $?

          # Render the rmarkdown document
          # $args = "-e", "rmarkdown::render('index-rmd.Rmd', output_file = 'index-rmd-r-x86.html')"
          # & $rscript $args

          # git config user.name "Tom Palmer"
          # git config user.email "remlapmot@hotmail.com"
          # git add index-rmd-r-x86.html
          # git commit -m "Update index-rmd-r-x86.html"
          # git push

      - name: Try on Git Bash
        run: |
          set +e

          # Rscript test.R
          # echo $?

          # Rscript "C:\ProgramData\Chocolatey\lib\quarto\tools\share\capabilities\knitr.R"
          # echo $?

          # Rscript test.R
          # echo $?
          
          Rscript knitr-end-newline.R
          echo $?

          Rscript -e 'requireNamespace("rmarkdown")'
          echo $?

          R -q -e 'requireNamespace("rmarkdown")'
          echo $?

          R -q -e 'requireNamespace("htmltools")'
          echo $?

          Rscript -e 'require("htmltools")'
          echo $?

          Rscript -e 'require("rmarkdown")'
          echo $?

          Rscript -e 'library("rmarkdown")'
          echo $?

          Rscript -e 'require("compiler")'
          echo $?

          Rscript -e 'require("fastmap")'
          echo $?

          Rscript -e 'require("cli")'
          echo $?

          Rscript -e 'require("tools")'
          echo $?

          Rscript -e 'require("rstudioapi")'
          echo $?

          Rscript -e 'require("digest")'
          echo $?

          Rscript -e 'require("rlang")'
          echo $?

        shell: bash
      # - name: Render the Quarto document
      #   run: |
      #     quarto --version
      #     quarto check knitr --log-level debug
      #     quarto render index.qmd --output index-r-x86.html

      #     # Commit and push
      #     git config user.name "Tom Palmer"
      #     git config user.email "remlapmot@hotmail.com"
      #     git add index-r-x86.html
      #     git commit -m "Update index-r-x86.html"
      #     git push
