on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:

name: win-11-arm-quarto-test-r-x86-2

permissions: write-all

jobs:
  R-CMD-check:
    runs-on: windows-11-arm

    name: windows-11-arm

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5
      
      - name: Render Quarto doc using x86_64 R 4.5.1
        run: |
          "Here 1"
          # Install R 4.5.1
          $url = "https://cran.r-project.org/bin/windows/base/R-4.5.1-win.exe"
          Invoke-WebRequest -Uri "$url" -OutFile R-x86_64.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath R-x86_64.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait

          "Here 2"
          # Install Rtools45
          # $url = "https://cran.r-project.org/bin/windows/Rtools/rtools45/files/rtools45-6608-6492.exe"
          # Invoke-WebRequest -Uri "$url" -OutFile rtools45.exe -UseBasicParsing -UserAgent "NativeHost"
          # Start-Process -FilePath rtools45.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait
          
          "Here 3"
          # Add R and Rtool45 binaries to PATH
          Get-ChildItem -Path "C:\Program Files (x86)\R\R-4.5.1\bin\x64"
          # $ENV:PATH = "C:\Program Files\R\R-4.5.1\bin\x64;C:\rtools45\usr\bin;$ENV:PATH"
          $ENV:PATH = "C:\Program Files (x86)\R\R-4.5.1\bin\x64"
          
          # Install pandoc
          # choco install pandoc
          
          "Here 4"
          # Install Quarto
          choco install quarto

          # Install TinyTeX
          $rscript = "Rscript"
          # $args = "-e", "install.packages(c('tinytex'), repos = 'https://cloud.r-project.org/'); tinytex::install_tinytex(); tinytex::tlmgr_install(c('makeindex', 'upquote', 'inconsolata'))"
          # & $rscript $args

          # Add TinyTeX binaries to PATH
          # $ENV:PATH = "C:\Users\runneradmin\AppData\Roaming\TinyTeX\bin\windows;$ENV:PATH"
          
          "Here 5"
          # Install knitr and rmarkdown
          $args = "-e", "install.packages(c('knitr', 'rmarkdown'), repos = 'https://cloud.r-project.org/');"
          & $rscript $args
          
          quarto --version
          quarto check
          quarto render index.qmd --output index-r-x86-2.html

      - name: Commit and push
        run: |
          git config user.name "Tom Palmer"
          git config user.email "remlapmot@hotmail.com"
          git add index-r-x86-2.html
          git commit -m "Update index-r-x86-2.html"
          git push
